# Generated by Django 4.2.11 on 2024-05-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='departement_de_travail',
        ),
    ]
