# Generated by Django 4.2.11 on 2024-05-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0003_remove_inventaire_sous_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='chef_de_departement',
        ),
    ]
