# Generated by Django 4.2.11 on 2024-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0004_remove_departement_chef_de_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_bar',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
