# Generated by Django 4.2.11 on 2024-05-22 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0007_remove_produit_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='warranty_period',
            field=models.IntegerField(default=0),
        ),
    ]
