# Generated by Django 4.2.11 on 2024-05-22 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0008_produit_date_added_alter_produit_warranty_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='date_added',
        ),
        migrations.AddField(
            model_name='produit',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='produit',
            name='warranty_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
