# Generated by Django 4.2.11 on 2024-05-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0009_remove_produit_date_added_produit_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
