# Generated by Django 4.2.11 on 2024-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0010_alter_produit_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='is_warranty_valid',
            new_name='warranty_isValid',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='warranty_description',
        ),
        migrations.AddField(
            model_name='produit',
            name='warranty_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='warranty_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
