# Generated by Django 4.2.11 on 2024-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0011_rename_is_warranty_valid_produit_warranty_isvalid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
