# Generated by Django 4.2.11 on 2024-05-23 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0012_produit_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
