# Generated by Django 4.2.11 on 2024-05-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0013_alter_produit_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='add_date',
        ),
    ]
