# Generated by Django 4.2.11 on 2024-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0014_remove_produit_add_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_pre_date', models.DateTimeField()),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('event_post_date', models.DateTimeField()),
                ('list_of_products', models.ManyToManyField(related_name='events', to='BeyondComV2.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('bucket_id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('products', models.ManyToManyField(related_name='buckets', to='BeyondComV2.produit')),
            ],
        ),
    ]
