# Generated by Django 4.2.11 on 2024-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0015_event_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='barcode',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
