# Generated by Django 4.2.11 on 2024-06-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0016_alter_bucket_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='list_of_buckets',
            field=models.ManyToManyField(related_name='events', to='BeyondComV2.bucket'),
        ),
    ]
