# Generated by Django 4.2.11 on 2024-06-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0017_event_list_of_buckets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='products',
            field=models.ManyToManyField(related_name='buckets', to='BeyondComV2.inventaire'),
        ),
        migrations.AlterField(
            model_name='event',
            name='list_of_products',
            field=models.ManyToManyField(related_name='events', to='BeyondComV2.inventaire'),
        ),
    ]
