# Generated by Django 5.1.2 on 2024-10-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0018_alter_bucket_products_alter_event_list_of_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='list_of_buckets',
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
    ]
