# Generated by Django 5.1.2 on 2024-10-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0019_remove_event_list_of_buckets_delete_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='old_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
