# Generated by Django 5.1.2 on 2024-10-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0020_inventaire_old_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
