# Generated by Django 5.1.2 on 2024-10-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeyondComV2', '0021_event_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
    ]
